### ISSUE TITLE
认证成功挂机一段时间后脚本卡死, 怀疑是心跳包的问题

### ISSUE THREAD

**Issue by starryloki** [forever765/esurfing_python3#2]
上个月开始启动脚本一段时间后软件卡死, 学校登录满47小时会强制下线并要求重新登录, 卡死后无法进行自动重新登录

**Comment by forever765** [comment]
抱歉，我所在的环境无法测试连续在线47小时的情况。

请自行测试所在学校是否需要开启心跳，如无需心跳保活，可于第118行下增加 exit(0)  ，认证成功后退出脚本，每天定时执行一次认证即可

**Comment by starryloki** [comment]
感谢解答
