### ISSUE TITLE
大佬您是华商的骄傲，广东的骄傲，大大的感谢

### ISSUE THREAD

**Issue by wslsq** [forever765/esurfing_python3#3]
自从10.20更新客户端版本以后一度绝望以为再无WiFi可用。
直到看到学长大佬的项目。
非常感谢！

曾以为旧的拨号方式关闭了，没想到只是获取验证码那路径加了个v。
不介意的话，请问大佬在哪里得到的最新路径和参数，我想学习一下，看到其他项目很多都没更新路径。

**Comment by forever765** [comment]
很高兴能帮到你，这也是我开源的初衷😀
天翼校园客户端和app都做了混淆和加密，想要拿到最新算法和密钥很麻烦，之前看过别人对掌上大学App的逆向，请求的参数应该就是从那里得到的。

**Comment by wslsq** [comment]
谢谢老哥！
